### ISSUE TITLE
BestRecordStructure Suggestion

### ISSUE THREAD

**Issue by GordonSmith** [hpcc-systems/DataPatterns#21]
As part of the BestRecordStructure output, it would be nice if it included a second line with a a suitable transform function (especially for all the STRING  -> REAL8 type conversions).

**Comment by dcamper** [comment]
The current version of BestRecordStructure returns a dataset, where every record is a "dataType fieldName;" declaration (wrapped by "RECORD" and "END" records) to make it relatively easy to copy and paste into an editor.

Adding another output means changing this function from returning a dataset to returning an action that outputs two datasets.  Do you think this change would negatively impact many current users?  The primary use case was not programmatic (e.g. the output is unlikely to consumed by other ECL code) but the possibility exists.

Thoughts?

**Comment by GordonSmith** [comment]
I would add more lines at the bottom that includes the transform + project?  When copying users can easily ignore if not wanted?

**Comment by dcamper** [comment]
Ha!  That is an excellent suggestion.

**Comment by dcamper** [comment]
Change just merged.
