### ISSUE TITLE
Include version in DP Output (if it doesn't exist already)

### ISSUE THREAD

**Issue by GordonSmith** [hpcc-systems/DataPatterns#38]
Embed the version of DataPatterns that created the output as part of the output (will be useful for backward compatibility once integrated into ECL Watch).

**Comment by dcamper** [comment]
@GordonSmith How do you envision that output to be represented?  As literally a result in the workunit, or perhaps as a stored variable?

**Comment by GordonSmith** [comment]
Not needed
