### ISSUE TITLE
Self test is failing

### ISSUE THREAD

**Issue by GordonSmith** [hpcc-systems/DataPatterns#40]
Source | Severity | Code | Message | FileName | LineNo | Column | id
------- | --------- | ------ | ---------- | ---------- | -------- | -------- | ----
user | Error | 100000 | Assert (integer8 = integer3) failed [best_attribute_type = 'integer3'] | /home/gordon/git/HPCC-Platform/ecllibrary/teststd/DataPatterns/TestDataPatterns.ecl | 88 | 88 | 0
user | Error | 100000 | Assert (unsigned4 = unsigned2) failed [best_attribute_type = 'unsigned2'] | /home/gordon/git/HPCC-Platform/ecllibrary/teststd/DataPatterns/TestDataPatterns.ecl | 417 | 417 | 1
user | Error | 100000 | Assert (unsigned4 = unsigned2) failed [best_attribute_type = 'unsigned2'] | /home/gordon/git/HPCC-Platform/ecllibrary/teststd/DataPatterns/TestDataPatterns.ecl | 438 | 438 | 2
user | Error | 100000 | Assert (unsigned4 = unsigned2) failed [best_attribute_type = 'unsigned2'] | /home/gordon/git/HPCC-Platform/ecllibrary/teststd/DataPatterns/TestDataPatterns.ecl | 459 | 459 | 3

**Comment by dcamper** [comment]
Tests were failing due to changes made in 1.3.4.  Tests have been updated.
