### ISSUE TITLE
Add function for Benford's Law test on a column

### ISSUE THREAD

**Issue by JamesDeFabia** [hpcc-systems/DataPatterns#66]
Benford’s law can be useful to detect fraud and data errors because it’s expected that certain large sets of numbers will follow the law.  I think it would be a great new feature for the Data Patterns library. It would be nice to have a function that could take a column of a data set and detect if it passes the Benford Test. 

Optionally, It would also be nice to make it possible to test specified columns for Benford distribution in ECL Watch when analyzing data files. This should be optional because it is not applicable to all data columns (or even all numeric data).

**Comment by dcamper** [comment]
Additional info:

https://www.statisticshowto.com/benfords-law/
https://en.wikipedia.org/wiki/Benford%27s_law

**Comment by dcamper** [comment]
Added to candidate-1.6.6.
